# Публикация пакета в npm + релиз на GitHub
# Триггер: push в main или тег-релиз вида vX.Y.Z
name: Publish & Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'     # только версии, совпадающие с семвер-тегом

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write        # нужно для создания релиза

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Устанавливаем Node LTS и включаем yarn-кэш
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'yarn'

      # 3. Ставим зависимости из yarn.lock
      - name: Install deps
        run: yarn install --frozen-lockfile

      # 4. Сборка библиотеки (скрипт уже есть в package.json)
      - name: Build package
        run: yarn build

      # 5. Публикуем в npm ТОЛЬКО при пуше тега-версии
      - name: Publish to npm
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: ./dist
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # 6. Создаём релиз с автоматическими релиз-нотами
      - name: GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
